# Generated by Django 4.1 on 2022-11-04 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='college',
            table='clg',
        ),
        migrations.AlterModelTable(
            name='principle',
            table='princi',
        ),
    ]
