# Generated by Django 4.1 on 2022-11-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_app', '0006_student_alter_department_college_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='address',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
