# Generated by Django 4.1 on 2022-11-04 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relation_app', '0008_alter_department_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='studs', to='relation_app.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depts', to='relation_app.college'),
        ),
    ]
