# Generated by Django 4.1 on 2022-11-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_app', '0009_student_department_alter_department_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='student',
            field=models.ManyToManyField(related_name='sub', to='relation_app.student'),
        ),
    ]
