# Generated by Django 4.1 on 2022-11-05 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relation_app', '0011_alter_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principle',
            name='college',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='relation_app.college'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studs', to='relation_app.department'),
        ),
    ]
